# 本番環境用
version: '3.8'

services:
  backend:
    build:
      context: ./KiloGram
      dockerfile: Dockerfile
      target: production  
    command: gunicorn kilogram_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes: []  
    environment:
      - DEBUG=False

  frontend:
    build:
      context: ./kilogram-app
      dockerfile: Dockerfile
      target: production  # Nginx + ビルド済みファイル
    ports:
      - "80:80"
    volumes: []

  celery:
    volumes: []

  celery-beat:
    volumes: []