# Generated by Django 5.2.4 on 2025-07-20 11:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.date.today, verbose_name='日付')),
                ('meal_timing', models.CharField(choices=[('breakfast', '朝食'), ('lunch', '昼食'), ('dinner', '夕食'), ('snack', '間食')], max_length=10, verbose_name='食事タイミング')),
                ('meal_name', models.CharField(max_length=100, verbose_name='食事名')),
                ('calories', models.FloatField(default=0.0, verbose_name='カロリー(kcal)')),
                ('protein', models.FloatField(default=0.0, verbose_name='タンパク質(g)')),
                ('fat', models.FloatField(default=0.0, verbose_name='脂質(g)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='炭水化物(g)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '食事記録',
                'verbose_name_plural': '食事記録',
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.date.today, unique_for_date='user', verbose_name='日付')),
                ('weight', models.FloatField(verbose_name='体重(kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '体重記録',
                'verbose_name_plural': '体重記録',
            },
        ),
    ]
