# Generated by Django 5.2.4 on 2025-07-21 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today, verbose_name='日付'),
        ),
    ]
