# Generated by Django 5.2.4 on 2025-08-31 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0002_alter_weightrecord_record_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_number', models.CharField(max_length=10, unique=True, verbose_name='食品番号')),
                ('name', models.CharField(max_length=100, verbose_name='食品名')),
                ('category', models.CharField(max_length=50, verbose_name='分類')),
                ('calories_per_100g', models.FloatField(verbose_name='エネルギー(kcal)')),
                ('protein_per_100g', models.FloatField(verbose_name='たんぱく質(g)')),
                ('fat_per_100g', models.FloatField(verbose_name='脂質(g)')),
                ('carbs_per_100g', models.FloatField(verbose_name='炭水化物(g)')),
                ('fiber_per_100g', models.FloatField(default=0, verbose_name='食物繊維(g)')),
                ('sodium_per_100g', models.FloatField(default=0, verbose_name='ナトリウム(mg)')),
                ('calcium_per_100g', models.FloatField(default=0, verbose_name='カルシウム(mg)')),
                ('iron_per_100g', models.FloatField(default=0, verbose_name='鉄(mg)')),
                ('vitamin_a_per_100g', models.FloatField(default=0, verbose_name='ビタミンA(μg)')),
                ('vitamin_b1_per_100g', models.FloatField(default=0, verbose_name='ビタミンB1(mg)')),
                ('vitamin_b2_per_100g', models.FloatField(default=0, verbose_name='ビタミンB2(mg)')),
                ('vitamin_c_per_100g', models.FloatField(default=0, verbose_name='ビタミンC(mg)')),
            ],
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='calcium',
            field=models.FloatField(default=0.0, verbose_name='カルシウム(mg)'),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='dietary_fiber',
            field=models.FloatField(default=0.0, verbose_name='食物繊維(g)'),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='iron',
            field=models.FloatField(default=0.0, verbose_name='鉄分(mg)'),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='sodium',
            field=models.FloatField(default=0.0, verbose_name='ナトリウム(mg)'),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='vitamin_a',
            field=models.FloatField(default=0.0, verbose_name='ビタミンA(μg)'),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='vitamin_b1',
            field=models.FloatField(default=0.0, verbose_name='ビタミンB1(mg)'),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='vitamin_b2',
            field=models.FloatField(default=0.0, verbose_name='ビタミンB2(mg)'),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='vitamin_c',
            field=models.FloatField(default=0.0, verbose_name='ビタミンC(mg)'),
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_100g', models.FloatField(verbose_name='エネルギー(kcal)')),
                ('protein_per_100g', models.FloatField(verbose_name='たんぱく質(g)')),
                ('fat_per_100g', models.FloatField(verbose_name='脂質(g)')),
                ('carbs_per_100g', models.FloatField(verbose_name='炭水化物(g)')),
                ('fiber_per_100g', models.FloatField(default=0, verbose_name='食物繊維(g)')),
                ('sodium_per_100g', models.FloatField(default=0, verbose_name='ナトリウム(mg)')),
                ('calcium_per_100g', models.FloatField(default=0, verbose_name='カルシウム(mg)')),
                ('iron_per_100g', models.FloatField(default=0, verbose_name='鉄(mg)')),
                ('vitamin_a_per_100g', models.FloatField(default=0, verbose_name='ビタミンA(μg)')),
                ('vitamin_b1_per_100g', models.FloatField(default=0, verbose_name='ビタミンB1(mg)')),
                ('vitamin_b2_per_100g', models.FloatField(default=0, verbose_name='ビタミンB2(mg)')),
                ('vitamin_c_per_100g', models.FloatField(default=0, verbose_name='ビタミンC(mg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
