# Generated by Django 5.2.4 on 2025-08-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0003_standardfood_mealrecord_calcium_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfood',
            options={'verbose_name': 'カスタム食品', 'verbose_name_plural': 'カスタム食品'},
        ),
        migrations.AlterModelOptions(
            name='standardfood',
            options={'verbose_name': '標準食品', 'verbose_name_plural': '標準食品'},
        ),
    ]
