# Generated by Django 5.x.x on 2025-10-08 14:55

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0005_cafeteriamenu'), 
    ]

    operations = [
        TrigramExtension(),
    ]