# Generated by Django 5.2.4 on 2025-10-14 06:21

import datetime
import django.contrib.postgres.indexes
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0006_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfood',
            options={'ordering': ['user', 'name'], 'verbose_name': 'カスタム食品', 'verbose_name_plural': 'カスタム食品'},
        ),
        migrations.AlterModelOptions(
            name='mealrecord',
            options={'ordering': ['-record_date', '-created_at'], 'verbose_name': '食事記録', 'verbose_name_plural': '食事記録'},
        ),
        migrations.AlterModelOptions(
            name='standardfood',
            options={'ordering': ['category', 'name'], 'verbose_name': '標準食品', 'verbose_name_plural': '標準食品'},
        ),
        migrations.AlterModelOptions(
            name='weightrecord',
            options={'ordering': ['-record_date'], 'verbose_name': '体重記録', 'verbose_name_plural': '体重記録'},
        ),
        migrations.AddField(
            model_name='customfood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='cafeteriamenu',
            name='category',
            field=models.CharField(choices=[('main', '主菜'), ('side', '副菜'), ('noodle', '麺類'), ('rice', '丼・カレー'), ('dessert', 'デザート'), ('order', 'オーダー'), ('kebab', 'ケバブ＆ベジタリアン'), ('parfait', 'パフェ'), ('night', '夜限定'), ('other', 'その他')], db_index=True, max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='cafeteriamenu',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='メニュー名'),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='record_date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='standardfood',
            name='category',
            field=models.CharField(db_index=True, max_length=50, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='standardfood',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='食品名'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='record_date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='日付'),
        ),
        migrations.AddIndex(
            model_name='cafeteriamenu',
            index=models.Index(fields=['category'], name='cafeteria_category_idx'),
        ),
        migrations.AddIndex(
            model_name='cafeteriamenu',
            index=models.Index(fields=['category', 'name'], name='cafeteria_cat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='cafeteriamenu',
            index=models.Index(fields=['updated_at'], name='cafeteria_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='customfood',
            index=models.Index(fields=['user', 'name'], name='customfood_user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customfood',
            index=models.Index(fields=['user'], name='customfood_user_idx'),
        ),
        migrations.AddIndex(
            model_name='mealrecord',
            index=models.Index(fields=['user', 'record_date'], name='meal_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mealrecord',
            index=models.Index(fields=['user', 'meal_timing'], name='meal_user_timing_idx'),
        ),
        migrations.AddIndex(
            model_name='mealrecord',
            index=models.Index(fields=['-created_at'], name='meal_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='standardfood',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='standardfood_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='standardfood',
            index=models.Index(fields=['category', 'name'], name='standardfood_cat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='standardfood',
            index=models.Index(fields=['category'], name='standardfood_category_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['user', 'record_date'], name='weight_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['user', '-record_date'], name='weight_user_date_desc_idx'),
        ),
    ]
