# Generated by Django 5.2.4 on 2026-09-07 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0010_googleaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(default=2000, verbose_name='エネルギー(kcal)')),
                ('protein', models.FloatField(default=100, verbose_name='たんぱく質(g)')),
                ('fat', models.FloatField(default=56, verbose_name='脂質(g)')),
                ('carbs', models.FloatField(default=275, verbose_name='炭水化物(g)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '栄養目標値',
                'verbose_name_plural': '栄養目標値',
            },
        ),
    ]
