# Generated by Django 5.2.4 on 2026-09-08 03:33

from django.db import migrations, models

# 廃止したカテゴリーコードは 'other' に寄せ、旧表示名を見出しとして残す。
# 既存行はすべてルネ由来（従来のスクレイパは t=650118 しか見ていなかった）
_RETIRED_CATEGORIES = {
    'order': 'オーダー',
    'kebab': 'ケバブ＆ベジタリアン',
    'parfait': 'パフェ',
    'night': '夜限定',
}
_KEPT_CATEGORIES = {
    'main': '主菜',
    'side': '副菜',
    'noodle': '麺類',
    'rice': '丼・カレー',
    'dessert': 'デザート',
    'other': 'その他',
}


def backfill_category_labels(apps, schema_editor):
    CafeteriaMenu = apps.get_model('record_app', 'CafeteriaMenu')
    for old_code, label in _RETIRED_CATEGORIES.items():
        CafeteriaMenu.objects.filter(category=old_code).update(
            category='other', category_label=label
        )
    for code, label in _KEPT_CATEGORIES.items():
        CafeteriaMenu.objects.filter(category=code, category_label='').update(
            category_label=label
        )


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0011_nutritiongoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafeteriamenu',
            options={'ordering': ['cafeteria', 'category', 'name'], 'verbose_name': '食堂メニュー', 'verbose_name_plural': '食堂メニュー'},
        ),
        migrations.AddField(
            model_name='cafeteriamenu',
            name='cafeteria',
            field=models.CharField(choices=[('rune', 'ルネカフェテリア'), ('hokubu', '北部食堂'), ('chuo', '中央食堂')], db_index=True, default='rune', max_length=20, verbose_name='食堂'),
        ),
        migrations.AddField(
            model_name='cafeteriamenu',
            name='category_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='カテゴリー見出し'),
        ),
        migrations.AlterField(
            model_name='cafeteriamenu',
            name='category',
            field=models.CharField(choices=[('main', '主菜'), ('side', '副菜'), ('noodle', '麺類'), ('rice', '丼・カレー'), ('dessert', 'デザート'), ('other', 'その他')], db_index=True, max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='cafeteriamenu',
            name='menu_id',
            field=models.CharField(max_length=20, verbose_name='メニューID'),
        ),
        migrations.AddIndex(
            model_name='cafeteriamenu',
            index=models.Index(fields=['cafeteria', 'category'], name='cafeteria_site_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='cafeteriamenu',
            constraint=models.UniqueConstraint(fields=('cafeteria', 'menu_id'), name='cafeteria_menu_unique'),
        ),
        migrations.RunPython(
            backfill_category_labels, migrations.RunPython.noop
        ),
    ]
