# Generated by Django 5.2.4 on 2025-11-20 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0007_alter_customfood_options_alter_mealrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='メニュー名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('total_calories', models.FloatField(default=0, verbose_name='合計カロリー(kcal)')),
                ('total_protein', models.FloatField(default=0, verbose_name='合計タンパク質(g)')),
                ('total_fat', models.FloatField(default=0, verbose_name='合計脂質(g)')),
                ('total_carbohydrates', models.FloatField(default=0, verbose_name='合計炭水化物(g)')),
                ('total_dietary_fiber', models.FloatField(default=0, verbose_name='合計食物繊維(g)')),
                ('total_sodium', models.FloatField(default=0, verbose_name='合計ナトリウム(mg)')),
                ('total_calcium', models.FloatField(default=0, verbose_name='合計カルシウム(mg)')),
                ('total_iron', models.FloatField(default=0, verbose_name='合計鉄分(mg)')),
                ('total_vitamin_a', models.FloatField(default=0, verbose_name='合計ビタミンA(μg)')),
                ('total_vitamin_b1', models.FloatField(default=0, verbose_name='合計ビタミンB1(mg)')),
                ('total_vitamin_b2', models.FloatField(default=0, verbose_name='合計ビタミンB2(mg)')),
                ('total_vitamin_c', models.FloatField(default=0, verbose_name='合計ビタミンC(mg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'Myメニュー',
                'verbose_name_plural': 'Myメニュー',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard', '標準食品'), ('custom', 'Myアイテム'), ('cafeteria', '食堂メニュー')], max_length=20, verbose_name='アイテム種別')),
                ('item_id', models.IntegerField(verbose_name='アイテムID')),
                ('item_name', models.CharField(max_length=200, verbose_name='アイテム名')),
                ('amount_grams', models.FloatField(verbose_name='分量(g)')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('calories', models.FloatField(verbose_name='カロリー(kcal)')),
                ('protein', models.FloatField(verbose_name='タンパク質(g)')),
                ('fat', models.FloatField(verbose_name='脂質(g)')),
                ('carbohydrates', models.FloatField(verbose_name='炭水化物(g)')),
                ('dietary_fiber', models.FloatField(default=0, verbose_name='食物繊維(g)')),
                ('sodium', models.FloatField(default=0, verbose_name='ナトリウム(mg)')),
                ('calcium', models.FloatField(default=0, verbose_name='カルシウム(mg)')),
                ('iron', models.FloatField(default=0, verbose_name='鉄分(mg)')),
                ('vitamin_a', models.FloatField(default=0, verbose_name='ビタミンA(μg)')),
                ('vitamin_b1', models.FloatField(default=0, verbose_name='ビタミンB1(mg)')),
                ('vitamin_b2', models.FloatField(default=0, verbose_name='ビタミンB2(mg)')),
                ('vitamin_c', models.FloatField(default=0, verbose_name='ビタミンC(mg)')),
                ('custom_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='record_app.custommenu', verbose_name='Myメニュー')),
            ],
            options={
                'verbose_name': 'メニューアイテム',
                'verbose_name_plural': 'メニューアイテム',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MealRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard', '標準食品'), ('custom', 'カスタム食品'), ('cafeteria', '食堂メニュー')], db_index=True, max_length=20, verbose_name='アイテム種別')),
                ('item_id', models.IntegerField(db_index=True, verbose_name='アイテムID')),
                ('item_name', models.CharField(max_length=200, verbose_name='アイテム名')),
                ('amount_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='分量(g)')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('calories', models.FloatField(default=0, verbose_name='エネルギー(kcal)')),
                ('protein', models.FloatField(default=0, verbose_name='タンパク質(g)')),
                ('fat', models.FloatField(default=0, verbose_name='脂質(g)')),
                ('carbohydrates', models.FloatField(default=0, verbose_name='炭水化物(g)')),
                ('dietary_fiber', models.FloatField(default=0, verbose_name='食物繊維(g)')),
                ('sodium', models.FloatField(default=0, verbose_name='食塩相当量(g)')),
                ('calcium', models.FloatField(default=0, verbose_name='カルシウム(mg)')),
                ('iron', models.FloatField(default=0, verbose_name='鉄(mg)')),
                ('vitamin_a', models.FloatField(default=0, verbose_name='ビタミンA(μg)')),
                ('vitamin_b1', models.FloatField(default=0, verbose_name='ビタミンB1(mg)')),
                ('vitamin_b2', models.FloatField(default=0, verbose_name='ビタミンB2(mg)')),
                ('vitamin_c', models.FloatField(default=0, verbose_name='ビタミンC(mg)')),
                ('meal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='record_app.mealrecord', verbose_name='食事記録')),
            ],
            options={
                'verbose_name': '食事記録アイテム',
                'verbose_name_plural': '食事記録アイテム',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='custommenu',
            index=models.Index(fields=['user', 'name'], name='custommenu_user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='custommenu',
            index=models.Index(fields=['user', '-created_at'], name='custommenu_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='custommenuitem',
            index=models.Index(fields=['custom_menu', 'display_order'], name='custommenuitem_menu_order_idx'),
        ),
        migrations.AddIndex(
            model_name='mealrecorditem',
            index=models.Index(fields=['meal_record', 'display_order'], name='mealitem_record_order_idx'),
        ),
        migrations.AddIndex(
            model_name='mealrecorditem',
            index=models.Index(fields=['item_type', 'item_id'], name='mealitem_polymorphic_idx'),
        ),
    ]
